FROM node:22.18.0-alpine

WORKDIR /usr/src/app

COPY package*.json ./
RUN npm install

RUN npm install -g nodemon

# Não copiamos o código aqui, ele vem pelo volume
EXPOSE 3001

CMD ["npm", "run", "dev"]
