FROM node:22.18.0-alpine

WORKDIR /usr/src/app

COPY package*.json ./
RUN npm install

# Não copiamos o código aqui, ele vem pelo volume
EXPOSE 5173

CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0"]
